spring:
  kafka:
    # Перечисляем всех наших брокеров
    bootstrap-servers: 192.168.1.20:9092
    producer:
      # Настраиваем сериализацию сообщений
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    test-topic: topic1
